repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.280'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/ambv/black
    rev: '22.3.0'
    hooks:
      - id: black
        language: python
        types: [ python ]
        args: [ "--line-length=120" ]